---
version: "3"

services:
  dt01:
    image: dt01
    build: build
    restart: always
    hostname: dt01
    ports:
      - "5901:5901" # VNC
      - "6901:6901" # noVNC
      - "2222:22"   # SSH
      - "4200:4200" # Shellinabox
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # OpenSSH server host keys
      # - ./hostkeys/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
      # - ./hostkeys/ssh_host_ecdsa_key.pub:/etc/ssh/ssh_host_ecdsa_key.pub:ro
      # - ./hostkeys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      # - ./hostkeys/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro
      # - ./hostkeys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      # - ./hostkeys/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro
      # Persistent data directory
      - data:/data
    environment:
      VNC_PASSWORD: mainuser

volumes:
  data: {}
