---
services:
  dt01:
    # Tested with docker.io/dmotte/desktainer:v2024.02.05.2216
    image: docker.io/dmotte/desktainer:latest
    restart: always
    hostname: dt01
    ports:
      - "5901:5901"
      - "6901:6901"
      - "2222:22"
      - "4200:4200"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ssh-host-keys:/etc/ssh/host-keys
      - data:/data
    environment:
      MAINUSER_PASS: mypassword
      MAINUSER_NOPASSWORD: "true"
      VNC_PASS: mypassword

volumes:
  ssh-host-keys: {}
  data: {}
