---
version: "3"

services:
  dt01:
    image: dt01
    build: build
    restart: always
    hostname: dt01
    ports:
      - "5901:5901"
      - "6901:6901"
      - "2222:22"
      - "4200:4200"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ssh-host-keys:/etc/ssh/host-keys
      - data:/data
    environment:
      PASSWORD: mypassword
      VNC_PASSWORD: mypassword
      PORTMAP_SSH_CLIENT_KEY: |-
        (put-private-ssh-key-here)
      LOGNOT_BOT_TOKEN: (put-bot-token-here)
      LOGNOT_CHAT_ID: (put-chat-id-here)

volumes:
  ssh-host-keys: {}
  data: {}
