---
version: "3"

services:
  dt01:
    image: dt01
    build: build
    restart: always
    hostname: dt01
    ports:
      - "5901:5901" # VNC
      - "6901:6901" # noVNC
      - "2222:22"   # SSH
      - "4200:4200" # Shellinabox
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # OpenSSH server host keys
      - ssh-host-keys:/etc/ssh/host-keys
      # Persistent data directory
      - data:/data
    environment:
      VNC_PASSWORD: mainuser

volumes:
  ssh-host-keys: {}
  data: {}
