---
version: "3"

services:
  desktainer:
    image: docker.io/dmotte/desktainer:latest
    build: build
    restart: always
    hostname: desktainer
    ports:
      - "5901:5901" # VNC
      - "6901:6901" # noVNC
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VNC_PASSWORD: mainuser
